spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true

server:
  port: 8081
  tomcat:
    compression: on
    compressableMimeTypes: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
